//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Poslodavac.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public class Poslodavac : Radnik{
	public void ZaposliRadnika(){
	}
	public void OtpustiRadnika(){
	}
}
