//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Recenzent.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public class Recenzent : Radnik{
	public void NapisiRecenziju(Igrica i){
	}
	public void OcjeniIgricu(Igrica i){
	}
}
