//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Radnik.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


private class Radnik : Osoba{
	private string Job ;
	private real Plata ;
	private integer RadnoVrijeme = 8;
	public Radnik(){
	}
	~Radnik(){
	}
	public string DajID(){
	}
}
