//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ShoppingCart.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public class ShoppingCart {
	private int UkupnaCijena ;
	private Igrica[1..*] IzabraneIgrice ;
	public int DajUkupnuCijenu(Igrica[1..*] IzabraneIgrice){
	}
}
