//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TipoviRegistracije.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public enum TipoviRegistracije {
	Mjesecni,
	Godisnji,
	All-Time
}
