//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Osoba.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public abstract class Osoba {
	private string Ime ;
	private object Prezime: string ;
	private object ID: string ;
	private object JMBG: integer ;
	private string Kontakt ;
	private string Adresa ;
	private string E-Mail ;
}
