//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Raèunar.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public class Raèunar {
	private string Sifra ;
	private boolean Dostupan ;
	public Racunar(){
	}
	~Racunar(){
	}
	public boolean DaLiJeDostupan(){
	}
	public void DajSifru(){
	}
}
