//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Raèunari.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public class Raèunari {
	private Raèunar[0..*] Computer ;
	private integer BrojDostupnih ;
	public void RezervisiRacunar(Raèunar r){
	}
	public void OslobodiRacunar(Raèunar r){
	}
	public void OslobodiSve(){
	}
	public void DostupnostRacunara(){
	}
	public integer ObracunajTermin(){
	}
	public void ObracunajPopust(TipoviRegistracije tip_kupca){
	}
}
