//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TipKlijenta.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public enum TipKlijenta {
	Obicni,
	Registrovani
}
