//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Uposlenik.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public class Uposlenik : Radnik{
	public void ProdajIgricu(Igrica i){
	}
	public void RegistrujKlijenta(Klijent k){
	}
}
