//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Platform.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public class Platform {
	private string Naziv ;
	public Klijent[0..*] Subscriberi ;
	public void SaljiSubskripcije(Klijent k){
	}
	public void DodajSubscribera(Klijent k){
	}
	public void IgriceZaPlatformu(){
	}
}
