//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Raèunovoða.cs
//  @ Date : 6.4.2014
//  @ Author : 
//
//


public class Raèunovoða : Radnik{
	public void IsplacujePlate(){
	}
}
